### ISSUE TITLE
Is this open source

### ISSUE THREAD

**Issue by krishnakanthpps** [lboddapati/bart#1]
Can I reuse it for Hyderabad? or can you help me build something similar for Hyderabad?

**Comment by lboddapati** [comment]
BART is bay area's public transit system. I built this application using BART's public APIs -> http://api.bart.gov/docs/overview/index.aspx

If this kind of information is available for Hyderabad, I'd be happy to help you with the project.

**Comment by krishnakanthpps** [comment]
I am looking to get some approval from Apsrtc and tsrtc.
